// STACKD TRADER — Dev mock data so the dashboard renders before Supabase
// is wired up. Replace each call with a real query when the bot goes online.

import type { BotStatus, RiskSettings, Signal, TradeMode } from '@/types/database';

export function mockBotStatus(mode: TradeMode): BotStatus {
  return {
    id: 'mock-status',
    mode,
    is_active: mode === 'paper',
    regime: 'trending',
    daily_pnl: mode === 'paper' ? 312.45 : 0,
    daily_trades: mode === 'paper' ? 4 : 0,
    daily_loss_limit_hit: false,
    paused_until: null,
    consecutive_losses: 0,
    paper_started_at: null,
    paper_starting_balance: null,
    last_updated: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
  };
}

export function mockRiskSettings(mode: TradeMode): RiskSettings {
  const isTopstep = mode === 'topstep';
  return {
    id: 'mock-risk',
    mode,
    max_risk_per_trade_pct: 1.0,
    daily_loss_limit_pct: 3.0,
    profit_target_pct: 6.0,
    max_contracts: isTopstep ? 2 : 5,
    is_topstep_mode: isTopstep,
    topstep_daily_loss_limit: 1000,
    topstep_max_drawdown: 2000,
    topstep_profit_target: 3000,
    updated_at: new Date().toISOString(),
  };
}

export function mockSignals(mode: TradeMode): Signal[] {
  const base = Date.now();
  const rows: Signal[] = [
    {
      id: 's1',
      mode,
      instrument: 'BTC/USD',
      strategy: 'momentum',
      direction: 'long',
      rsi: 62.1,
      macd: 0.42,
      macd_histogram: 0.12,
      volume_ratio: 1.8,
      key_level_break: true,
      atr: 421.5,
      regime: 'trending',
      raw_score: 76.5,
      sentiment_score: 7.1,
      total_score: 84,
      action: 'enter',
      claude_explanation: 'Strong momentum with volume confirmation above 64k breakout level.',
      created_at: new Date(base - 1000 * 60 * 1).toISOString(),
    },
    {
      id: 's2',
      mode,
      instrument: 'MES',
      strategy: 'mean_reversion',
      direction: 'long',
      rsi: 28.4,
      macd: -0.18,
      macd_histogram: -0.04,
      volume_ratio: 1.1,
      key_level_break: false,
      atr: 12.4,
      regime: 'ranging',
      raw_score: 56.0,
      sentiment_score: 1.0,
      total_score: 62,
      action: 'skip',
      claude_explanation: 'Oversold but no catalyst. Holding off until volume picks up.',
      created_at: new Date(base - 1000 * 60 * 7).toISOString(),
    },
    {
      id: 's3',
      mode,
      instrument: 'ETH/USD',
      strategy: 'news_sentiment',
      direction: 'long',
      rsi: 55.0,
      macd: 0.21,
      macd_histogram: 0.08,
      volume_ratio: 2.4,
      key_level_break: true,
      atr: 38.2,
      regime: 'trending',
      raw_score: 82.5,
      sentiment_score: 8.8,
      total_score: 91,
      action: 'enter',
      claude_explanation: 'Positive ETF news plus key level break. High conviction.',
      created_at: new Date(base - 1000 * 60 * 14).toISOString(),
    },
    {
      id: 's4',
      mode,
      instrument: 'MNQ',
      strategy: 'momentum',
      direction: 'long',
      rsi: 70.2,
      macd: 0.55,
      macd_histogram: 0.21,
      volume_ratio: 1.4,
      key_level_break: true,
      atr: 48.7,
      regime: 'trending',
      raw_score: 66.0,
      sentiment_score: 4.0,
      total_score: 70,
      action: 'enter',
      claude_explanation: 'Trend continuation, but overbought. Sizing down.',
      created_at: new Date(base - 1000 * 60 * 22).toISOString(),
    },
    {
      id: 's5',
      mode,
      instrument: 'BTC/USD',
      strategy: 'mean_reversion',
      direction: 'short',
      rsi: 41.3,
      macd: -0.05,
      macd_histogram: -0.01,
      volume_ratio: 0.9,
      key_level_break: false,
      atr: 380.0,
      regime: 'ranging',
      raw_score: 39.0,
      sentiment_score: 2.0,
      total_score: 41,
      action: 'skip',
      claude_explanation: 'No edge. Volume is below average and sentiment is mixed.',
      created_at: new Date(base - 1000 * 60 * 31).toISOString(),
    },
  ];
  return rows;
}
